### ISSUE TITLE
What qtile version is supported?

### ISSUE THREAD

**Issue by nazar-pc** [numirias/qtile-plasma#10]
I'm getting following error both with 0.10.7 and recently released 0.11.0:
```
During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/nazar-pc/.local/lib/python3.6/site-packages/plasma/layout.py", line 64, in add
    self.root.restore(new)
  File "/home/nazar-pc/.local/lib/python3.6/site-packages/plasma/node.py", line 560, in restore
    raise NotRestorableError()
plasma.node.NotRestorableError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/nazar-pc/.local/bin/qtile", line 11, in <module>
    load_entry_point('qtile', 'console_scripts', 'qtile')()
  File "/web/github/qtile/libqtile/scripts/qtile.py", line 125, in main
    q = make_qtile()
  File "/web/github/qtile/libqtile/scripts/qtile.py", line 119, in make_qtile
    state=options.state,
  File "/web/github/qtile/libqtile/manager.py", line 245, in __init__
    self.scan()
  File "/web/github/qtile/libqtile/manager.py", line 568, in scan
    self.manage(item)
  File "/web/github/qtile/libqtile/manager.py", line 627, in manage
    c = window.Window(w, self)
  File "/web/github/qtile/libqtile/window.py", line 770, in __init__
    group.add(self)
  File "/web/github/qtile/libqtile/group.py", line 270, in add
    i.add(win)
  File "/home/nazar-pc/.local/lib/python3.6/site-packages/plasma/layout.py", line 66, in add
    node.add_node(new, self.add_mode)
  File "/home/nazar-pc/.local/lib/python3.6/site-packages/plasma/node.py", line 539, in add_node
    self.parent.add_child_after(node, self)
  File "/home/nazar-pc/.local/lib/python3.6/site-packages/plasma/node.py", line 498, in add_child_after
    self.add_child(new, idx=old.index+1)
  File "/home/nazar-pc/.local/lib/python3.6/site-packages/plasma/node.py", line 495, in add_child
    Node.fit_into(node.siblings, total - (total / len(self)))
TypeError: unsupported operand type(s) for /: 'NoneType' and 'int'
```

**Comment by numirias** [comment]
Thanks for reporting!

I think I found a way to reproduce the bug. Will let you know when I got it fixed.

**Comment by numirias** [comment]
The bug is triggered when windows are added to the layout but the layout's `configure()` has not yet been called. In that case the screen dimensions are still unknown to the layout and it tries to do math with `None` values.

Do you mind checking if the patch fixes the problem for you?

**Comment by flacjacket** [comment]
Is this an issue on the qtile side? It seems like that shouldn't be
happening.

**Comment by nazar-pc** [comment]
#11 works for me
