### ISSUE TITLE
Installation is failing on Ubuntu 18

### ISSUE THREAD

**Issue by 4544fa8d** [numirias/qtile-plasma#19]
After executing `pip3 install --upgrade qtile-plasma` i see errors:

```
    100% |████████████████████████████████| 245kB 679kB/s 
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-jnoa60a6/qtile/setup.py", line 71, in <module>
        'libqtile/core/xcursors_ffi_build.py:xcursors_ffi',
      File "/usr/lib/python3/dist-packages/setuptools/__init__.py", line 128, in setup
        _install_setup_requires(attrs)
      File "/usr/lib/python3/dist-packages/setuptools/__init__.py", line 121, in _install_setup_requires
        dist.parse_config_files(ignore_option_errors=True)
      File "/usr/lib/python3/dist-packages/setuptools/dist.py", line 494, in parse_config_files
        ignore_option_errors=ignore_option_errors)
      File "/usr/lib/python3/dist-packages/setuptools/config.py", line 110, in parse_configuration
        options.parse()
      File "/usr/lib/python3/dist-packages/setuptools/config.py", line 380, in parse
        self.section_prefix, section_name))
    distutils.errors.DistutilsOptionError: Unsupported distribution option section: [options.data_files]
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-jnoa60a6/qtile/
```

My qtile version: 0.10.7 (installed with sudo apt install qtile).

**Comment by g-wizzy** [comment]
qtile version should be at least 0.14.2, as far as I can see.

I just installed it on Ubuntu 18.04 as well, and it works without any problem.

**Comment by numirias** [comment]
Closing because affected versions are outdated by now.
