### ISSUE TITLE
Error in `from plasma import Plasma` for new python version.

### ISSUE THREAD

**Issue by SweepingBishops** [numirias/qtile-plasma#27]
Arch recently updated python to 3.11, since then I have not been able to use Plasma. Running 
`python config.py` gives the error

```
Traceback (most recent call last):
  File "/home/roshan/.config/qtile/config.py", line 11, in <module>
    from plasma import Plasma
  File "/home/roshan/.local/lib/python3.11/site-packages/plasma/__init__.py", line 1, in <module>
    from .layout import Plasma
  File "/home/roshan/.local/lib/python3.11/site-packages/plasma/layout.py", line 6, in <module>
    from .node import Node, AddMode, NotRestorableError
  File "/home/roshan/.local/lib/python3.11/site-packages/plasma/node.py", line 20, in <module>
    HORIZONTAL, VERTICAL = Orient
    ^^^^^^^^^^^^^^^^^^^^
ValueError: not enough values to unpack (expected 2, got 1)
```
This error is just because of the import, it persists even if I'm not using the library ever again in the config.

**Comment by jrwrigh** [comment]
Probably too late, but you just need to reinstall plasma for the new python version. I'm currently having issues getting plasma to work with Python 3.11, but I'll open a new issue for that. I'm guessing that might require an actual patch from the looks of it though...
